# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2safGnTNgniV9n99x7Cw-YZTAzxb6Rt
"""

import matplotlib.pyplot as plt

VIS1_MEAN = 292.8
AUD1_MEAN = 291.4
VIS1_STD = 23.03
AUD1_STD = 29.32

# build a bar plot
plt.bar(['Person 1 Visual', 'Person 1 Auditory'],[VIS1_MEAN, AUD1_MEAN], yerr=[VIS1_STD, AUD1_STD], capsize=10)
plt.ylabel('Speed (msec)')
plt.xlabel("Reflex Type")
plt.title('Reflex Speed, Visual vs. Auditory')

